module

public import SparseMonotiles.ContactCertificateDataIndexed5Base
public import SparseMonotiles.ContactCertificateFullTools

@[expose] public section

namespace SparseMonotiles.Contact.IndexedData5
set_option maxRecDepth 100000
set_option maxHeartbeats 0

def fullMates4105 : MateCertificate 160 := ⟨13, 117, fun i => (if i.val < 80 then (if i.val < 40 then (if i.val < 20 then (if i.val < 10 then none else (if i.val < 15 then (if i.val < 12 then none else (if i.val < 13 then none else (if i.val < 14 then some 117 else none))) else (if i.val < 17 then none else (if i.val < 18 then none else (if i.val < 19 then some 97 else none))))) else (if i.val < 30 then none else (if i.val < 35 then (if i.val < 32 then none else (if i.val < 33 then none else (if i.val < 34 then some 36 else none))) else (if i.val < 37 then none else (if i.val < 38 then none else (if i.val < 39 then some 16 else none)))))) else (if i.val < 60 then (if i.val < 50 then none else (if i.val < 55 then (if i.val < 52 then none else (if i.val < 53 then none else (if i.val < 54 then some 112 else none))) else (if i.val < 57 then none else (if i.val < 58 then none else (if i.val < 59 then some 92 else none))))) else (if i.val < 70 then none else (if i.val < 75 then (if i.val < 72 then none else (if i.val < 73 then none else (if i.val < 74 then some 31 else none))) else (if i.val < 77 then none else (if i.val < 78 then none else (if i.val < 79 then none else some 11))))))) else (if i.val < 120 then (if i.val < 100 then (if i.val < 90 then none else (if i.val < 95 then (if i.val < 92 then none else (if i.val < 93 then none else (if i.val < 94 then none else some 107))) else (if i.val < 97 then none else (if i.val < 98 then none else (if i.val < 99 then none else some 87))))) else (if i.val < 110 then none else (if i.val < 115 then (if i.val < 112 then none else (if i.val < 113 then none else (if i.val < 114 then none else some 26))) else none))) else (if i.val < 140 then (if i.val < 130 then (if i.val < 125 then (if i.val < 122 then (if i.val < 121 then some 6 else none) else none) else none) else (if i.val < 135 then none else (if i.val < 137 then (if i.val < 136 then some 102 else none) else none))) else (if i.val < 150 then (if i.val < 145 then (if i.val < 142 then (if i.val < 141 then none else some 82) else none) else none) else (if i.val < 155 then none else (if i.val < 157 then none else (if i.val < 158 then some 21 else none)))))))⟩
def fullMates4106 : MateCertificate 160 := ⟨13, 117, fun i => (if i.val < 80 then (if i.val < 40 then (if i.val < 20 then (if i.val < 10 then none else (if i.val < 15 then (if i.val < 12 then none else (if i.val < 13 then none else (if i.val < 14 then some 117 else none))) else (if i.val < 17 then none else (if i.val < 18 then none else (if i.val < 19 then some 36 else none))))) else (if i.val < 30 then none else (if i.val < 35 then (if i.val < 32 then none else (if i.val < 33 then none else (if i.val < 34 then some 97 else none))) else (if i.val < 37 then none else (if i.val < 38 then none else (if i.val < 39 then some 16 else none)))))) else (if i.val < 60 then (if i.val < 50 then none else (if i.val < 55 then (if i.val < 52 then none else (if i.val < 53 then none else (if i.val < 54 then some 107 else none))) else (if i.val < 57 then none else (if i.val < 58 then none else (if i.val < 59 then some 26 else none))))) else (if i.val < 70 then none else (if i.val < 75 then (if i.val < 72 then none else (if i.val < 73 then none else (if i.val < 74 then some 87 else none))) else (if i.val < 77 then none else (if i.val < 78 then none else (if i.val < 79 then none else some 6))))))) else (if i.val < 120 then (if i.val < 100 then (if i.val < 90 then none else (if i.val < 95 then (if i.val < 92 then none else (if i.val < 93 then none else (if i.val < 94 then none else some 112))) else (if i.val < 97 then none else (if i.val < 98 then none else (if i.val < 99 then none else some 31))))) else (if i.val < 110 then none else (if i.val < 115 then (if i.val < 112 then none else (if i.val < 113 then none else (if i.val < 114 then none else some 92))) else none))) else (if i.val < 140 then (if i.val < 130 then (if i.val < 125 then (if i.val < 122 then (if i.val < 121 then some 11 else none) else none) else none) else (if i.val < 135 then none else (if i.val < 137 then (if i.val < 136 then some 102 else none) else none))) else (if i.val < 150 then (if i.val < 145 then (if i.val < 142 then (if i.val < 141 then none else some 21) else none) else none) else (if i.val < 155 then none else (if i.val < 157 then none else (if i.val < 158 then some 82 else none)))))))⟩
def fullMates4141 : MateCertificate 160 := ⟨13, 139, fun i => (if i.val < 80 then (if i.val < 40 then (if i.val < 20 then (if i.val < 10 then none else (if i.val < 15 then (if i.val < 12 then none else (if i.val < 13 then none else (if i.val < 14 then some 139 else none))) else (if i.val < 17 then none else (if i.val < 18 then none else (if i.val < 19 then some 129 else none))))) else (if i.val < 30 then none else (if i.val < 35 then (if i.val < 32 then none else (if i.val < 33 then none else (if i.val < 34 then some 98 else none))) else (if i.val < 37 then none else (if i.val < 38 then none else (if i.val < 39 then some 88 else none)))))) else (if i.val < 60 then (if i.val < 50 then none else (if i.val < 55 then (if i.val < 52 then none else (if i.val < 53 then none else (if i.val < 54 then some 57 else none))) else (if i.val < 57 then none else (if i.val < 58 then none else (if i.val < 59 then some 47 else none))))) else (if i.val < 70 then none else (if i.val < 75 then (if i.val < 72 then none else (if i.val < 73 then none else (if i.val < 74 then some 17 else none))) else (if i.val < 77 then none else (if i.val < 78 then none else (if i.val < 79 then none else some 7))))))) else (if i.val < 120 then (if i.val < 100 then (if i.val < 90 then none else (if i.val < 95 then (if i.val < 92 then none else (if i.val < 93 then none else (if i.val < 94 then none else some 134))) else (if i.val < 97 then none else (if i.val < 98 then none else (if i.val < 99 then none else some 124))))) else (if i.val < 110 then none else (if i.val < 115 then (if i.val < 112 then none else (if i.val < 113 then none else (if i.val < 114 then none else some 93))) else none))) else (if i.val < 140 then (if i.val < 130 then (if i.val < 125 then (if i.val < 122 then (if i.val < 121 then some 83 else none) else none) else none) else (if i.val < 135 then none else (if i.val < 137 then (if i.val < 136 then some 52 else none) else none))) else (if i.val < 150 then (if i.val < 145 then (if i.val < 142 then (if i.val < 141 then none else some 42) else none) else none) else (if i.val < 155 then none else (if i.val < 157 then none else (if i.val < 158 then some 12 else none)))))))⟩
def fullMates4142 : MateCertificate 160 := ⟨13, 139, fun i => (if i.val < 80 then (if i.val < 40 then (if i.val < 20 then (if i.val < 10 then none else (if i.val < 15 then (if i.val < 12 then none else (if i.val < 13 then none else (if i.val < 14 then some 139 else none))) else (if i.val < 17 then none else (if i.val < 18 then none else (if i.val < 19 then some 98 else none))))) else (if i.val < 30 then none else (if i.val < 35 then (if i.val < 32 then none else (if i.val < 33 then none else (if i.val < 34 then some 129 else none))) else (if i.val < 37 then none else (if i.val < 38 then none else (if i.val < 39 then some 88 else none)))))) else (if i.val < 60 then (if i.val < 50 then none else (if i.val < 55 then (if i.val < 52 then none else (if i.val < 53 then none else (if i.val < 54 then some 134 else none))) else (if i.val < 57 then none else (if i.val < 58 then none else (if i.val < 59 then some 93 else none))))) else (if i.val < 70 then none else (if i.val < 75 then (if i.val < 72 then none else (if i.val < 73 then none else (if i.val < 74 then some 124 else none))) else (if i.val < 77 then none else (if i.val < 78 then none else (if i.val < 79 then none else some 83))))))) else (if i.val < 120 then (if i.val < 100 then (if i.val < 90 then none else (if i.val < 95 then (if i.val < 92 then none else (if i.val < 93 then none else (if i.val < 94 then none else some 57))) else (if i.val < 97 then none else (if i.val < 98 then none else (if i.val < 99 then none else some 17))))) else (if i.val < 110 then none else (if i.val < 115 then (if i.val < 112 then none else (if i.val < 113 then none else (if i.val < 114 then none else some 47))) else none))) else (if i.val < 140 then (if i.val < 130 then (if i.val < 125 then (if i.val < 122 then (if i.val < 121 then some 7 else none) else none) else none) else (if i.val < 135 then none else (if i.val < 137 then (if i.val < 136 then some 52 else none) else none))) else (if i.val < 150 then (if i.val < 145 then (if i.val < 142 then (if i.val < 141 then none else some 12) else none) else none) else (if i.val < 155 then none else (if i.val < 157 then none else (if i.val < 158 then some 42 else none)))))))⟩
def fullAccept022 : List (IndexedRow 5 160) := [
  ⟨Pose.ofCodes perm15 23 11204, .accepted fullMates4105⟩,
  ⟨Pose.ofCodes perm19 23 11204, .accepted fullMates4106⟩,
  ⟨Pose.ofCodes perm16 23 11204, .accepted fullMates4141⟩,
  ⟨Pose.ofCodes perm3 23 11204, .accepted fullMates4142⟩
]
theorem fullAccept022_checked : indexedValidate geometry fullAccept022 = true := by decide
theorem fullAccept022_length : fullAccept022.length = 4 := by rfl
def fullAccept022Output : List (Pose 5) := [Pose.ofCodes perm15 23 11204, Pose.ofCodes perm19 23 11204, Pose.ofCodes perm16 23 11204, Pose.ofCodes perm3 23 11204]
theorem fullAccept022_output : indexedAcceptedPoses fullAccept022 = fullAccept022Output := by rfl
#print axioms fullAccept022_checked
end SparseMonotiles.Contact.IndexedData5
