module

public import SparseMonotiles.ContactCertificateDataIndexed5Base
public import SparseMonotiles.ContactCertificateFullTools

@[expose] public section

namespace SparseMonotiles.Contact.IndexedData5
set_option maxRecDepth 100000
set_option maxHeartbeats 0

def fullMates2613 : MateCertificate 160 := ⟨8, 138, fun i => (if i.val < 80 then (if i.val < 40 then (if i.val < 20 then (if i.val < 10 then (if i.val < 5 then none else (if i.val < 7 then none else (if i.val < 8 then none else (if i.val < 9 then some 138 else none)))) else none) else (if i.val < 30 then (if i.val < 25 then (if i.val < 22 then none else (if i.val < 23 then none else (if i.val < 24 then some 77 else none))) else (if i.val < 27 then none else (if i.val < 28 then none else (if i.val < 29 then some 56 else none)))) else none)) else (if i.val < 60 then (if i.val < 50 then (if i.val < 45 then (if i.val < 42 then none else (if i.val < 43 then none else (if i.val < 44 then some 155 else none))) else (if i.val < 47 then none else (if i.val < 48 then none else (if i.val < 49 then some 133 else none)))) else none) else (if i.val < 70 then (if i.val < 65 then (if i.val < 62 then none else (if i.val < 63 then none else (if i.val < 64 then some 71 else none))) else (if i.val < 67 then none else (if i.val < 68 then none else (if i.val < 69 then some 51 else none)))) else none))) else (if i.val < 120 then (if i.val < 100 then (if i.val < 90 then (if i.val < 85 then (if i.val < 82 then none else (if i.val < 83 then none else (if i.val < 84 then none else some 149))) else (if i.val < 87 then none else (if i.val < 88 then none else (if i.val < 89 then none else some 128)))) else none) else (if i.val < 110 then (if i.val < 105 then (if i.val < 102 then none else (if i.val < 103 then none else (if i.val < 104 then none else some 66))) else (if i.val < 107 then none else (if i.val < 108 then none else (if i.val < 109 then none else some 46)))) else none)) else (if i.val < 140 then (if i.val < 130 then (if i.val < 125 then none else (if i.val < 127 then (if i.val < 126 then some 144 else none) else none)) else (if i.val < 135 then (if i.val < 132 then (if i.val < 131 then some 123 else none) else none) else none)) else (if i.val < 150 then (if i.val < 145 then none else (if i.val < 147 then (if i.val < 146 then none else some 61) else none)) else (if i.val < 155 then (if i.val < 152 then (if i.val < 151 then none else some 41) else none) else none)))))⟩
def fullMates2618 : MateCertificate 160 := ⟨8, 141, fun i => (if i.val < 80 then (if i.val < 40 then (if i.val < 20 then (if i.val < 10 then (if i.val < 5 then none else (if i.val < 7 then none else (if i.val < 8 then none else (if i.val < 9 then some 141 else none)))) else none) else (if i.val < 30 then (if i.val < 25 then (if i.val < 22 then none else (if i.val < 23 then none else (if i.val < 24 then some 157 else none))) else (if i.val < 27 then none else (if i.val < 28 then none else (if i.val < 29 then some 135 else none)))) else none)) else (if i.val < 60 then (if i.val < 50 then (if i.val < 45 then (if i.val < 42 then none else (if i.val < 43 then none else (if i.val < 44 then some 79 else none))) else (if i.val < 47 then none else (if i.val < 48 then none else (if i.val < 49 then some 58 else none)))) else none) else (if i.val < 70 then (if i.val < 65 then (if i.val < 62 then none else (if i.val < 63 then none else (if i.val < 64 then some 73 else none))) else (if i.val < 67 then none else (if i.val < 68 then none else (if i.val < 69 then some 53 else none)))) else none))) else (if i.val < 120 then (if i.val < 100 then (if i.val < 90 then (if i.val < 85 then (if i.val < 82 then none else (if i.val < 83 then none else (if i.val < 84 then none else some 120))) else (if i.val < 87 then none else (if i.val < 88 then none else (if i.val < 89 then none else some 99)))) else none) else (if i.val < 110 then (if i.val < 105 then (if i.val < 102 then none else (if i.val < 103 then none else (if i.val < 104 then none else some 114))) else (if i.val < 107 then none else (if i.val < 108 then none else (if i.val < 109 then none else some 94)))) else none)) else (if i.val < 140 then (if i.val < 130 then (if i.val < 125 then none else (if i.val < 127 then (if i.val < 126 then some 38 else none) else none)) else (if i.val < 135 then (if i.val < 132 then (if i.val < 131 then some 18 else none) else none) else none)) else (if i.val < 150 then (if i.val < 145 then none else (if i.val < 147 then (if i.val < 146 then none else some 33) else none)) else (if i.val < 155 then (if i.val < 152 then (if i.val < 151 then none else some 13) else none) else none)))))⟩
def fullMates2630 : MateCertificate 160 := ⟨8, 150, fun i => (if i.val < 80 then (if i.val < 40 then (if i.val < 20 then (if i.val < 10 then (if i.val < 5 then none else (if i.val < 7 then none else (if i.val < 8 then none else (if i.val < 9 then some 150 else none)))) else none) else (if i.val < 30 then (if i.val < 25 then (if i.val < 22 then none else (if i.val < 23 then none else (if i.val < 24 then some 119 else none))) else (if i.val < 27 then none else (if i.val < 28 then none else (if i.val < 29 then some 108 else none)))) else none)) else (if i.val < 60 then (if i.val < 50 then (if i.val < 45 then (if i.val < 42 then none else (if i.val < 43 then none else (if i.val < 44 then some 78 else none))) else (if i.val < 47 then none else (if i.val < 48 then none else (if i.val < 49 then some 67 else none)))) else none) else (if i.val < 70 then (if i.val < 65 then (if i.val < 62 then none else (if i.val < 63 then none else (if i.val < 64 then some 37 else none))) else (if i.val < 67 then none else (if i.val < 68 then none else (if i.val < 69 then some 27 else none)))) else none))) else (if i.val < 120 then (if i.val < 100 then (if i.val < 90 then (if i.val < 85 then (if i.val < 82 then none else (if i.val < 83 then none else (if i.val < 84 then none else some 156))) else (if i.val < 87 then none else (if i.val < 88 then none else (if i.val < 89 then none else some 145)))) else none) else (if i.val < 110 then (if i.val < 105 then (if i.val < 102 then none else (if i.val < 103 then none else (if i.val < 104 then none else some 113))) else (if i.val < 107 then none else (if i.val < 108 then none else (if i.val < 109 then none else some 103)))) else none)) else (if i.val < 140 then (if i.val < 130 then (if i.val < 125 then none else (if i.val < 127 then (if i.val < 126 then some 72 else none) else none)) else (if i.val < 135 then (if i.val < 132 then (if i.val < 131 then some 62 else none) else none) else none)) else (if i.val < 150 then (if i.val < 145 then none else (if i.val < 147 then (if i.val < 146 then none else some 32) else none)) else (if i.val < 155 then (if i.val < 152 then (if i.val < 151 then none else some 22) else none) else none)))))⟩
def fullMates2635 : MateCertificate 160 := ⟨8, 153, fun i => (if i.val < 80 then (if i.val < 40 then (if i.val < 20 then (if i.val < 10 then (if i.val < 5 then none else (if i.val < 7 then none else (if i.val < 8 then none else (if i.val < 9 then some 153 else none)))) else none) else (if i.val < 30 then (if i.val < 25 then (if i.val < 22 then none else (if i.val < 23 then none else (if i.val < 24 then some 80 else none))) else (if i.val < 27 then none else (if i.val < 28 then none else (if i.val < 29 then some 69 else none)))) else none)) else (if i.val < 60 then (if i.val < 50 then (if i.val < 45 then (if i.val < 42 then none else (if i.val < 43 then none else (if i.val < 44 then some 121 else none))) else (if i.val < 47 then none else (if i.val < 48 then none else (if i.val < 49 then some 110 else none)))) else none) else (if i.val < 70 then (if i.val < 65 then (if i.val < 62 then none else (if i.val < 63 then none else (if i.val < 64 then some 39 else none))) else (if i.val < 67 then none else (if i.val < 68 then none else (if i.val < 69 then some 29 else none)))) else none))) else (if i.val < 120 then (if i.val < 100 then (if i.val < 90 then (if i.val < 85 then (if i.val < 82 then none else (if i.val < 83 then none else (if i.val < 84 then none else some 142))) else (if i.val < 87 then none else (if i.val < 88 then none else (if i.val < 89 then none else some 131)))) else none) else (if i.val < 110 then (if i.val < 105 then (if i.val < 102 then none else (if i.val < 103 then none else (if i.val < 104 then none else some 59))) else (if i.val < 107 then none else (if i.val < 108 then none else (if i.val < 109 then none else some 49)))) else none)) else (if i.val < 140 then (if i.val < 130 then (if i.val < 125 then none else (if i.val < 127 then (if i.val < 126 then some 100 else none) else none)) else (if i.val < 135 then (if i.val < 132 then (if i.val < 131 then some 90 else none) else none) else none)) else (if i.val < 150 then (if i.val < 145 then none else (if i.val < 147 then (if i.val < 146 then none else some 19) else none)) else (if i.val < 155 then (if i.val < 152 then (if i.val < 151 then none else some 9) else none) else none)))))⟩
def fullAccept012 : List (IndexedRow 5 160) := [
  ⟨Pose.ofCodes perm15 23 9832, .accepted fullMates2613⟩,
  ⟨Pose.ofCodes perm4 23 9832, .accepted fullMates2618⟩,
  ⟨Pose.ofCodes perm16 23 9832, .accepted fullMates2630⟩,
  ⟨Pose.ofCodes perm9 23 9832, .accepted fullMates2635⟩
]
theorem fullAccept012_checked : indexedValidate geometry fullAccept012 = true := by decide
theorem fullAccept012_length : fullAccept012.length = 4 := by rfl
def fullAccept012Output : List (Pose 5) := [Pose.ofCodes perm15 23 9832, Pose.ofCodes perm4 23 9832, Pose.ofCodes perm16 23 9832, Pose.ofCodes perm9 23 9832]
theorem fullAccept012_output : indexedAcceptedPoses fullAccept012 = fullAccept012Output := by rfl
#print axioms fullAccept012_checked
end SparseMonotiles.Contact.IndexedData5
