module

public import SparseMonotiles.ContactCertificateDataIndexed5Base
public import SparseMonotiles.ContactCertificateFullTools

@[expose] public section

namespace SparseMonotiles.Contact.IndexedData5
set_option maxRecDepth 100000
set_option maxHeartbeats 0

def fullMates2774 : MateCertificate 160 := ⟨9, 81, fun i => (if i.val < 80 then (if i.val < 40 then (if i.val < 20 then (if i.val < 10 then (if i.val < 5 then none else (if i.val < 7 then none else (if i.val < 8 then none else (if i.val < 9 then none else some 81)))) else (if i.val < 15 then none else (if i.val < 17 then none else (if i.val < 18 then none else (if i.val < 19 then none else some 91))))) else (if i.val < 30 then (if i.val < 25 then none else (if i.val < 27 then none else (if i.val < 28 then none else (if i.val < 29 then none else some 122)))) else (if i.val < 35 then none else (if i.val < 37 then none else (if i.val < 38 then none else (if i.val < 39 then none else some 132)))))) else (if i.val < 60 then (if i.val < 50 then (if i.val < 45 then none else (if i.val < 47 then none else (if i.val < 48 then none else (if i.val < 49 then none else some 86)))) else (if i.val < 55 then none else (if i.val < 57 then none else (if i.val < 58 then none else (if i.val < 59 then none else some 96))))) else (if i.val < 70 then (if i.val < 65 then none else (if i.val < 67 then none else (if i.val < 68 then none else (if i.val < 69 then none else some 127)))) else none))) else (if i.val < 120 then (if i.val < 100 then (if i.val < 90 then (if i.val < 85 then (if i.val < 82 then (if i.val < 81 then some 137 else none) else none) else none) else (if i.val < 95 then (if i.val < 92 then (if i.val < 91 then some 101 else none) else none) else none)) else (if i.val < 110 then (if i.val < 105 then (if i.val < 102 then (if i.val < 101 then some 111 else none) else none) else none) else (if i.val < 115 then (if i.val < 112 then (if i.val < 111 then some 143 else none) else none) else none))) else (if i.val < 140 then (if i.val < 130 then (if i.val < 125 then (if i.val < 122 then (if i.val < 121 then none else some 154) else none) else none) else (if i.val < 135 then (if i.val < 132 then (if i.val < 131 then none else some 106) else none) else none)) else (if i.val < 150 then (if i.val < 145 then (if i.val < 142 then none else (if i.val < 143 then some 116 else none)) else none) else (if i.val < 155 then (if i.val < 152 then none else (if i.val < 153 then none else (if i.val < 154 then some 148 else none))) else none)))))⟩
def fullMates2775 : MateCertificate 160 := ⟨9, 81, fun i => (if i.val < 80 then (if i.val < 40 then (if i.val < 20 then (if i.val < 10 then (if i.val < 5 then none else (if i.val < 7 then none else (if i.val < 8 then none else (if i.val < 9 then none else some 81)))) else (if i.val < 15 then none else (if i.val < 17 then none else (if i.val < 18 then none else (if i.val < 19 then none else some 101))))) else (if i.val < 30 then (if i.val < 25 then none else (if i.val < 27 then none else (if i.val < 28 then none else (if i.val < 29 then none else some 86)))) else (if i.val < 35 then none else (if i.val < 37 then none else (if i.val < 38 then none else (if i.val < 39 then none else some 106)))))) else (if i.val < 60 then (if i.val < 50 then (if i.val < 45 then none else (if i.val < 47 then none else (if i.val < 48 then none else (if i.val < 49 then none else some 122)))) else (if i.val < 55 then none else (if i.val < 57 then none else (if i.val < 58 then none else (if i.val < 59 then none else some 143))))) else (if i.val < 70 then (if i.val < 65 then none else (if i.val < 67 then none else (if i.val < 68 then none else (if i.val < 69 then none else some 127)))) else none))) else (if i.val < 120 then (if i.val < 100 then (if i.val < 90 then (if i.val < 85 then (if i.val < 82 then (if i.val < 81 then some 148 else none) else none) else none) else (if i.val < 95 then (if i.val < 92 then (if i.val < 91 then some 91 else none) else none) else none)) else (if i.val < 110 then (if i.val < 105 then (if i.val < 102 then (if i.val < 101 then some 111 else none) else none) else none) else (if i.val < 115 then (if i.val < 112 then (if i.val < 111 then some 96 else none) else none) else none))) else (if i.val < 140 then (if i.val < 130 then (if i.val < 125 then (if i.val < 122 then (if i.val < 121 then none else some 116) else none) else none) else (if i.val < 135 then (if i.val < 132 then (if i.val < 131 then none else some 132) else none) else none)) else (if i.val < 150 then (if i.val < 145 then (if i.val < 142 then none else (if i.val < 143 then some 154 else none)) else none) else (if i.val < 155 then (if i.val < 152 then none else (if i.val < 153 then none else (if i.val < 154 then some 137 else none))) else none)))))⟩
def fullMates2831 : MateCertificate 160 := ⟨9, 117, fun i => (if i.val < 80 then (if i.val < 40 then (if i.val < 20 then (if i.val < 10 then (if i.val < 5 then none else (if i.val < 7 then none else (if i.val < 8 then none else (if i.val < 9 then none else some 117)))) else (if i.val < 15 then none else (if i.val < 17 then none else (if i.val < 18 then none else (if i.val < 19 then none else some 36))))) else (if i.val < 30 then (if i.val < 25 then none else (if i.val < 27 then none else (if i.val < 28 then none else (if i.val < 29 then none else some 112)))) else (if i.val < 35 then none else (if i.val < 37 then none else (if i.val < 38 then none else (if i.val < 39 then none else some 31)))))) else (if i.val < 60 then (if i.val < 50 then (if i.val < 45 then none else (if i.val < 47 then none else (if i.val < 48 then none else (if i.val < 49 then none else some 107)))) else (if i.val < 55 then none else (if i.val < 57 then none else (if i.val < 58 then none else (if i.val < 59 then none else some 26))))) else (if i.val < 70 then (if i.val < 65 then none else (if i.val < 67 then none else (if i.val < 68 then none else (if i.val < 69 then none else some 102)))) else none))) else (if i.val < 120 then (if i.val < 100 then (if i.val < 90 then (if i.val < 85 then (if i.val < 82 then (if i.val < 81 then some 21 else none) else none) else none) else (if i.val < 95 then (if i.val < 92 then (if i.val < 91 then some 97 else none) else none) else none)) else (if i.val < 110 then (if i.val < 105 then (if i.val < 102 then (if i.val < 101 then some 16 else none) else none) else none) else (if i.val < 115 then (if i.val < 112 then (if i.val < 111 then some 92 else none) else none) else none))) else (if i.val < 140 then (if i.val < 130 then (if i.val < 125 then (if i.val < 122 then (if i.val < 121 then none else some 11) else none) else none) else (if i.val < 135 then (if i.val < 132 then (if i.val < 131 then none else some 87) else none) else none)) else (if i.val < 150 then (if i.val < 145 then (if i.val < 142 then none else (if i.val < 143 then some 6 else none)) else none) else (if i.val < 155 then (if i.val < 152 then none else (if i.val < 153 then none else (if i.val < 154 then some 82 else none))) else none)))))⟩
def fullMates2832 : MateCertificate 160 := ⟨9, 117, fun i => (if i.val < 80 then (if i.val < 40 then (if i.val < 20 then (if i.val < 10 then (if i.val < 5 then none else (if i.val < 7 then none else (if i.val < 8 then none else (if i.val < 9 then none else some 117)))) else (if i.val < 15 then none else (if i.val < 17 then none else (if i.val < 18 then none else (if i.val < 19 then none else some 97))))) else (if i.val < 30 then (if i.val < 25 then none else (if i.val < 27 then none else (if i.val < 28 then none else (if i.val < 29 then none else some 107)))) else (if i.val < 35 then none else (if i.val < 37 then none else (if i.val < 38 then none else (if i.val < 39 then none else some 87)))))) else (if i.val < 60 then (if i.val < 50 then (if i.val < 45 then none else (if i.val < 47 then none else (if i.val < 48 then none else (if i.val < 49 then none else some 112)))) else (if i.val < 55 then none else (if i.val < 57 then none else (if i.val < 58 then none else (if i.val < 59 then none else some 92))))) else (if i.val < 70 then (if i.val < 65 then none else (if i.val < 67 then none else (if i.val < 68 then none else (if i.val < 69 then none else some 102)))) else none))) else (if i.val < 120 then (if i.val < 100 then (if i.val < 90 then (if i.val < 85 then (if i.val < 82 then (if i.val < 81 then some 82 else none) else none) else none) else (if i.val < 95 then (if i.val < 92 then (if i.val < 91 then some 36 else none) else none) else none)) else (if i.val < 110 then (if i.val < 105 then (if i.val < 102 then (if i.val < 101 then some 16 else none) else none) else none) else (if i.val < 115 then (if i.val < 112 then (if i.val < 111 then some 26 else none) else none) else none))) else (if i.val < 140 then (if i.val < 130 then (if i.val < 125 then (if i.val < 122 then (if i.val < 121 then none else some 6) else none) else none) else (if i.val < 135 then (if i.val < 132 then (if i.val < 131 then none else some 31) else none) else none)) else (if i.val < 150 then (if i.val < 145 then (if i.val < 142 then none else (if i.val < 143 then some 11 else none)) else none) else (if i.val < 155 then (if i.val < 152 then none else (if i.val < 153 then none else (if i.val < 154 then some 21 else none))) else none)))))⟩
def fullAccept016 : List (IndexedRow 5 160) := [
  ⟨Pose.ofCodes perm11 16 15206, .accepted fullMates2774⟩,
  ⟨Pose.ofCodes perm13 16 15206, .accepted fullMates2775⟩,
  ⟨Pose.ofCodes perm10 15 11204, .accepted fullMates2831⟩,
  ⟨Pose.ofCodes perm3 15 11204, .accepted fullMates2832⟩
]
theorem fullAccept016_checked : indexedValidate geometry fullAccept016 = true := by decide
theorem fullAccept016_length : fullAccept016.length = 4 := by rfl
def fullAccept016Output : List (Pose 5) := [Pose.ofCodes perm11 16 15206, Pose.ofCodes perm13 16 15206, Pose.ofCodes perm10 15 11204, Pose.ofCodes perm3 15 11204]
theorem fullAccept016_output : indexedAcceptedPoses fullAccept016 = fullAccept016Output := by rfl
#print axioms fullAccept016_checked
end SparseMonotiles.Contact.IndexedData5
